### PR TITLE
strings.xml in Brazilian Portuguese

### PR DESCRIPTION
**Pull request by Gabriel-Campos**
strings.xml in Brazilian Portuguese

### CODE REVIEW

**Comment by Rijul-Ahuja** [comment]
Hi, thanks for this. Will be merged in next release.
Would you by any chance know what the folder is supposed to be called? I can't find it on Google that easily. values-PT-rbr ?

**Comment by Rijul-Ahuja** [comment]
Hi, I figured it out. I can't directly merge your pull request because I had not seen it on time, so it causes some merge conflicts with yours. But I have manually added it to the app. Can you please provide a link to your homepage so I can add your name in the about screen?

**Comment by Gabriel-Campos** [comment]
Hi, you can put the name as Gabriel Campos.
Thanks

**Comment by Rijul-Ahuja** [comment]
Do you have any website or facebook that I could link to? I can also use your github or leave it blank. Let me know, thanks.

**Comment by Gabriel-Campos** [comment]
www.facebook.com/zzzgabriel
Thanks.

**Comment by Rijul-Ahuja** [comment]
Error while compile
will_restart_systemui
pref_restart_systemui
disable_knock_screen
reboot_unexpected not translated. Can you please see to it? Thanks.

**Comment by Rijul-Ahuja** [comment]
Manually merged. Next time, please make a folder for your language and then file the request. Make sure you pull the latest commit first. (Sorry, I am just starting out with Git, don't know enough to cover all cases). Thanks!

**Comment by Rijul-Ahuja** [comment]
Gabriel, could you please translate the few English strings? If you are well versed with Git, file another pull request, or just put them here. I will add them.
https://github.com/Rijul-Ahuja/Xposed-Knock-Code/blob/master/app/src/main/res/values-pt-rBR/strings.xml#L55

**Pull request closed without merging**
